"""add phone number"

Revision ID: 600de84b5a13
Revises: 3e93b10af073
Create Date: 2022-04-20 22:48:55.216657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600de84b5a13'
down_revision = '3e93b10af073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
